name: helx

dependencies:
  - python=3.9
  - pip
  - pip:
     - black
     - flake8
     - pytest
     - jax
     - jax_dataclasses
     - chex
     - optax
     - rlax
     - flax
     - dm_env
     - wandb
     - absl-py
     - gymnasium[all]
     - bsuite