name: Examples

on:
  workflow_call:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  examples:
    runs-on: ubuntu-latest
    steps:
    - name: Run examples
      run: |
        wandb login ${{ secrets.WANDB_API_KEY }}
        for f in examples/*.py; do python $f; done