name: Code quality

on:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/download-artifact@master
      with:
        name: "setup"
        path: ./artifacts

    - name: Check code quality
      run: |
        pip install pylint
        MESSAGE=$(pylint -ry $(git ls-files '*.py') ||:)
        echo "$MESSAGE"