name: Code quality

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Check code quality
      run: |
        pip install pylint
        MESSAGE=$(pylint -ry $(git ls-files '*.py') ||:)
        echo "$MESSAGE"