name: Pytest

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Run unit tests with pytest
      run: pytest test/