name: Pytest

on:
  workflow_call:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Run unit tests with pytest
      run: pytest test/