name: Linting

on: [push]

jobs:
  Test:
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: ["ubuntu"]
    continue-on-error: false


    steps:

    - uses: .github/workflows/setup.yml

    - uses: .github/workflows/linting.yml

    - uses: .github/workflows/pytest.yml

    - uses: .github/workflows/examples.yml